name: Comandos workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje de warning y error
        run: |
          echo "Mensaje normal"
          echo "::warning:: Mensaje de advertencia"
          echo "::error::Este es un mensaje de error"
    
