name: Expresiones ejemplo

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sistema_operativo: [windows-latest, ubuntu-latest, macos-latest]
    name: matriz-unidimensional
    runs-on: ${{matrix.sistema_operativo}}
    steps:
      - name: paso solo para Win
        if: ${{matrix.sistema_operativo == 'windows-latest'}}
        run: echo "Solo se ejecuta en WINDOWS"

      - name: paso para todos los SOs
        run: echo "Paso común para todos"
    
