name: Variables

on:
  workflow_dispatch:

env:
  variable_global: VARIABLE_GLOBAL

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      variable_job: VARIABLE JOBS
    steps:
      - name: step 1 del job 1
        run: |
          echo el valor de la variable global es $variable_global
          echo 'otra forma de escribir la variable es ${{ env.variable_global }}'
          echo 'tambien podemos definir variables a nivel de un único job: ${{env.variable_job}}'
